up:
	vagrant up

rm:	
	vagrant destroy -f

test1:
	curl -H "Host:app1.com" 192.168.42.110

test2:
	curl -H "Host:app2.com" 192.168.42.110

test3:
	curl -H "Host:app3.com" 192.168.42.110

test: test1 test2 test3
