Vagrant.configure(2) do |config|
    config.vm.box = "centos/8"

    config.vm.define "ndubouilS" do |control|
        control.vm.hostname = "ndubouilS"
        control.vm.network "private_network", ip: "192.168.42.110"
        control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--cpus", "1"]
            v.customize ["modifyvm", :id, "--memory", "1024"]
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
            v.customize ["modifyvm", :id, "--name", "p1-ndubouilS"]
        end
        control.vm.provision "shell", path: "install_server.sh"
        control.vm.provision "shell", inline: "kubectl apply -f /vagrant/conf", privileged: false
    end
end
  