Vagrant.configure(2) do |config|
    $common = <<-SHELL
    sudo yum -y install vim tree net-tools telnet git python3
    sudo echo "alias python=/usr/bin/python3" >> /home/vagrant/.bashrc
    sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
    sudo systemctl restart sshd
    SHELL

    config.vm.box = "centos/8"

    config.vm.define "ndubouilS" do |control|
        control.vm.hostname = "ndubouilS"
        control.vm.network "private_network", ip: "192.168.42.110"
        control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--cpus", "1"]
            v.customize ["modifyvm", :id, "--memory", "1024"]
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
            v.customize ["modifyvm", :id, "--name", "p1-ndubouilS"]
        end
        # config.vm.provision "shell", inline: $common
        control.vm.provision "shell", path: "install_server.sh"
        control.trigger.after :up do |trigger|
            trigger.info = "Rsync local files"
            trigger.run = {
              inline: "bash -c 'vagrant ssh -c \"sudo cat /var/lib/rancher/k3s/server/node-token\" ndubouilS > token'"
            }
          end
    end

    config.vm.define "ndubouilSW" do |control|
        control.vm.hostname = "ndubouilSW"
        control.vm.network "private_network", ip: "192.168.42.111"
        control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--cpus", "1"]
            v.customize ["modifyvm", :id, "--memory", "512"]
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
            v.customize ["modifyvm", :id, "--name", "p1-ndubouilSW"]
        end
        control.vm.provision "shell", path: "install_worker.sh"
        # config.vm.provision :shell, :inline => $common
    end
end
  