apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: iotplayground-project
  labels:
    app: iotplayground
spec:
  # Project description
  description: Iot Playground application
  # Allow manifests to deploy only from Sokube git repositories 
  sourceRepos:
  - "https://github.com/nirae/*"
  # Only permit to deploy applications in the same cluster
  destinations:
  - namespace: dev
    server: https://kubernetes.default.svc
  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false
